### ISSUE TITLE
Documentation: clarifications of inputs for MatchGrains script

### ISSUE THREAD

**Issue by StopkaKris** [marinerhemant/MIDAS#9]
Hi,

It would be useful to add further documentation of the input parameters for the [MatchGrains](https://github.com/marinerhemant/MIDAS/blob/master/FF_HEDM/src/MatchGrains.c) script, including

stateN.txt: 
- A file containing a list of Grains.csv files or a Grains.csv file directly.
- **If a list of Grains.csv files is provided, the results will be merged into a single file.**

**SGnr:**
- **Space group number (e.g., 225 for most common FCC systems)**

Also, in what scenario would the user provide an input for ```referenceMisorientation```? This could use an explanation similar to the one provided for the two options of ```removeDuplicates```.

Best regards,
Kris

Krzysztof Stopka

**Comment by marinerhemant** [comment]
Nice catch. I've submitted updates.

**Comment by StopkaKris** [comment]
Hi Hemant,

Could we please also add documentation clarifying in what scenario the user would provide an input for ```referenceMisorientation```?

**Comment by marinerhemant** [comment]
Done, please see the latest commit https://github.com/marinerhemant/MIDAS/commit/357c87fe62782f60c9605b2b65b60a7d0f2d1ec3
